Repository SuomixxXXxx/food-root-server, pull requests merged in 2024-10, with the labels that each got.

#21 dto serialization
  src/main/java/org/chiches/foodrootservir/dto/CategoryDTO.java
  src/main/java/org/chiches/foodrootservir/dto/DishItemDTO.java
  src/main/java/org/chiches/foodrootservir/dto/OrderContentDTO.java
  src/main/java/org/chiches/foodrootservir/dto/OrderDTO.java
  src/main/java/org/chiches/foodrootservir/entities/OrderEntity.java
Labels: improvement

#22 Code Cleanup: Extracted Duplicate Logic into a Function
  src/main/java/org/chiches/foodrootservir/config/MapperConfig.java
  src/main/java/org/chiches/foodrootservir/services/impl/DishItemServiceImpl.java
  src/main/java/org/chiches/foodrootservir/services/impl/OrderServiceImpl.java
Labels: improvement

#23 the authority initializer
  src/main/java/org/chiches/foodrootservir/config/AuthorityInitializer.java
  src/main/java/org/chiches/foodrootservir/repositories/AuthorityRepository.java
  src/main/resources/application.properties
Labels: enhancement

#24 Pdf reports
  pom.xml
  src/main/java/org/chiches/foodrootservir/controllers/StaffController.java
  src/main/java/org/chiches/foodrootservir/repositories/OrderContentRepository.java
  src/main/java/org/chiches/foodrootservir/repositories/OrderRepository.java
  src/main/java/org/chiches/foodrootservir/services/PdfService.java
  src/main/java/org/chiches/foodrootservir/services/impl/PdfServiceImpl.java
Labels: enhancement

#25 new endpoint
  src/main/java/org/chiches/foodrootservir/controllers/DishItemController.java
  src/main/java/org/chiches/foodrootservir/repositories/DishItemRepository.java
  src/main/java/org/chiches/foodrootservir/services/DishItemService.java
  src/main/java/org/chiches/foodrootservir/services/impl/DishItemServiceImpl.java
  src/main/java/org/chiches/foodrootservir/services/impl/PdfServiceImpl.java
  src/main/resources/Times_New_Roman.ttf
Labels: enhancement

#26 Cors + auth tweaks
  src/main/java/org/chiches/foodrootservir/config/SecurityConfig.java
  src/main/java/org/chiches/foodrootservir/config/WebConfig.java
  src/main/java/org/chiches/foodrootservir/repositories/RefreshTokenRepository.java
Labels: enhancement

#27 Feature/web sockets
  .gitignore
  pom.xml
  src/main/java/org/chiches/foodrootservir/config/JacksonConfig.java
  src/main/java/org/chiches/foodrootservir/config/OrderWebSocketHandler.java
  src/main/java/org/chiches/foodrootservir/config/SecurityConfig.java
  src/main/java/org/chiches/foodrootservir/config/WebSocketConfig.java
  src/main/java/org/chiches/foodrootservir/controllers/AuthController.java
  src/main/java/org/chiches/foodrootservir/dto/TokenDTO.java
  src/main/java/org/chiches/foodrootservir/dto/UserDTO.java
  src/main/java/org/chiches/foodrootservir/entities/CategoryEntity.java
  src/main/java/org/chiches/foodrootservir/entities/DishItemEntity.java
  src/main/java/org/chiches/foodrootservir/entities/OrderContentEntity.java
  src/main/java/org/chiches/foodrootservir/entities/OrderEntity.java
  src/main/java/org/chiches/foodrootservir/entities/RefreshTokenEntity.java
  src/main/java/org/chiches/foodrootservir/entities/UserEntity.java
  src/main/java/org/chiches/foodrootservir/repositories/OrderRepository.java
  src/main/java/org/chiches/foodrootservir/security/RefreshTokenService.java
  src/main/java/org/chiches/foodrootservir/services/AuthenticationService.java
  src/main/java/org/chiches/foodrootservir/services/MessagesService.java
  src/main/java/org/chiches/foodrootservir/services/OrderService.java
  src/main/java/org/chiches/foodrootservir/services/impl/AuthenticationServiceImpl.java
  src/main/java/org/chiches/foodrootservir/services/impl/MessagesServiceImpl.java
  src/main/java/org/chiches/foodrootservir/services/impl/OrderServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#28 Feature/search endpoint
  src/main/java/org/chiches/foodrootservir/config/SecurityConfig.java
  src/main/java/org/chiches/foodrootservir/controllers/DishItemController.java
  src/main/java/org/chiches/foodrootservir/repositories/DishItemRepository.java
  src/main/java/org/chiches/foodrootservir/services/DishItemService.java
  src/main/java/org/chiches/foodrootservir/services/impl/DishItemServiceImpl.java
  src/main/java/org/chiches/foodrootservir/services/impl/OrderServiceImpl.java
Labels: enhancement

#30 Hotfix
  src/main/java/org/chiches/foodrootservir/services/impl/DishItemServiceImpl.java
Labels: bug
